### ISSUE TITLE
multi digit input is not working   

### ISSUE THREAD

**Issue by 5um4n7h** [tarunsraina/Simple-Calculator#1]
@tarunsraina , Input field is taking only single digit, 
If user clicks on any number, input field is replacing by that number
It seems error is in OnClickListners of number Buttons

 ```
button0.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                info.setText(result.getText().toString()+"0");
            }
        });
 ```

numbers should be concatenate with previous value of EditText info

**Comment by taruntej-a** [comment]
Thanks @5um4n7h ,I have fixed the issue.
